
# FortiGate Configuration Script BOOTSTRAP
config system global
    set hostname "BOOTSTRAP_01"
end

# Step 1: Remove internal3-5 from the hardware switch
config system virtual-switch
    edit "internal"
        config port
            delete "internal5"
            delete "internal4"
            delete "internal3"
        end
    next
end

# Step 2: Configure the independent interface
config system interface
    edit "internal5"
        set mode static
        set ip 10.20.30.1 255.255.255.0
        set allowaccess ping https ssh
    next
end

# Step 2: Configure the independent interface ABB
config system interface
    edit "internal3"
        set mode static
        set ip 10.20.106.5 255.255.255.0
        set allowaccess ping https ssh
    next
end

# Step 3: Configure DHCP Server
config system dhcp server
    edit 1
        set interface "internal5"
        set status enable
        set netmask 255.255.255.0
        config ip-range
            edit 1
                set start-ip 10.20.30.41
                set end-ip 10.20.30.51
            next
        end
    next
end

# Step 4: Syslog and SNMP
config log syslogd setting
    set status enable
    set server "grafana.cs.lab"
end

config system snmp community
    edit 1
        set name "SecSi"
        config hosts
            edit 1
                set ip 10.0.1.19 255.255.255.255
            next
        end
    next
end

# Step 5: Secure the Admin with your Trusted Hosts
config system admin
    edit "admin"
        set trusthost1 109.247.29.111 255.255.255.255
        set trusthost2 85.252.22.53 255.255.255.255
    next
end

# Step 6: Disable USB auto-install after this run (Security)
#config system auto-install
#    set auto-install-config disable
#    set auto-install-image disable
#end

