[fortigates]
my_firewall ansible_host=192.168.10.99

[fortigates:vars]
ansible_user=admin
ansible_password=KankeHuskeAlt1!
ansible_network_os=fortinet.fortios.fortios
ansible_connection=httpapi
ansible_httpapi_use_ssl=yes
ansible_httpapi_validate_certs=no
ansible_httpapi_port=443
